# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bba64de059625fe5a76bfdd6f8a5a0db0a9bac4d75f586e41d24250f62581e7932d9722975090e8be20b569488fba0914a5b44c972b8f1dbfd456b5fa44565c0

test:
  secret_key_base: 43fc647261f963ce974116e587eb1b65b377f8b3b80fda58a1149ed1ec84b9bbbac6776104fb4088649aa2f3161128b58ebb85e5968c76140f152f1de6e4bd9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
